label begin(channel="Station"):
    n "You are on the second floor."
    run (table_1_start, table_2_start, table_3_start)
    n "Next up is the main course."

label table_1_start(channel="Table 1 Name"):
    bao "Hello"
    yan "Hello"
    zl  "Hello"

label table_2_start(channel="Table 2 Name"):
    ld "Hello"
    min "Hello"
    gw "Hello"

label table_3_start(channel="Table 3 Name"):
    cf "Hello"
    mg "Hello"
    bgn "Hello"
    cj "Hello"
