# Copyright (C) 2026 Placeholder Name
# SPDX-License-Identifier: GPL-3.0-only

default num_players = 0
default ready_count = 0

label setup:
    time limit 15 minutes
    # jump act_1.begin
    # jump act_1.quiz_1
    jump show_num_player_promot
    # jump act_1.table_1_start

label show_num_player_promot(channel="Meta"):
    n "This game is designed for 2 to 3 players."
    n "You may want to communicate with others or write things down."
    n "In that case, feel free to do so in any way you want."
    n "You can also check out the dialog by yourself. But it would be hard to 'win' alone; the game expects multiple players who will split themselves up and listen to different ongoing conversations."
    # testing
    # $ ready_count = 1
    # $ num_players = 1
    # jump act_1.begin
    jump get_num_players

label get_num_players(channel="Meta"):
    input "Please tell me the number of players. Just the arabic number please." into num_players:
        case "1":
            $ num_players = 1
        case "2":
            $ num_players = 2
        case "3":
            $ num_players = 3
        case _:
            jump get_num_players 
    button "Continue?":

    jump start

label start(channel="Meta"):
    n "The hanging red banner says:"
    n "New Journey, Original Mission - Celebrating 50 years of Silk Manufacturing"
    n "1953 - 2003"

    m "Make no mistake!"
    m "This is an easy job; you will each be assigned to one table at this banquet."
    m "Your tables have a bunch of seniors who retired from the Factory a while ago!"
    m "Just humor them if they try to talk to you. As waiters, you should try to make the customers happy. "
    m "Go to your shifts!"
    jump ask_all_ready

label bomb_start(channel="Botanical Gardens"):
    m "So I'll say it again:"
    wait 5
    m "Your performance tonight is very important."
    n "Your manager has gathered you under an old willow tree."
    n "The restaurant is just visible across the road."
    n "The hanging red banner says:"
    n "New Journey, Original Mission - Celebrating 50 years of Silk Manufacturing"
    n "1953 - 2003"
    m "Before I became the manager, I was a waiter just like you!"
    m "So I know the job, and really, it's simple!"
    n "Crickets are singing enthusiastically. It's summer."
    m "Each of you will stay next to a table!"
    m "And serve dishes that arrive from the kitchen!"
    m "And fill up their cups!"
    m "Lastly, there are some seniors at your tables who retired from the Factory decades ago."
    m "Just humor them if they try to talk to you, old people can be lonely."
    m "Dismissed!"
    m "As the manager tries to leave, a young server suddenly runs out from the restaurant and shows him a piece of paper."
    n "He turns pale as he reads it."
    wait 3
    m "You'd better see this."
    n "He shows you the paper, which is yellow with age. It has the Silk Factory's official letterhead. It only has a short message, which is written neatly on a fountain pen:"
    n "Dear staff, I have placed an explosive gift in your scenic establishment. If you search for it or contact the police, it will detonate. If you cooperate, I promise no one innocent will be hurt."
    n "Signed, Mister Bomb"

    server "I just checked, and all the phone wires have been cut!"
    m "They are serious! I, I thought this only happened in movies!"
    n "Your manager eventually recovers some cool."
    m "Who could have written this?"
    n "It's early, only a few guests have arrived at the restaurant."
    n "A group of 60-somethings are making conversation on the balcony."
    server "Those are retirees from the Factory and the only guests right now."
    m "Which makes them ... our only suspects."
    n "He looks at the neat hand-writing again."
    m "No one else could have the factory's letter paper!"

    m "You all keep your eyes open and your mouth shut!"
    m "I'll assign you to the tables where they are sitting."
    
    n "Welcome to the game!"
    n "Your goal here is to investigate the bomb threat over the course of the banquet."
    n "If you do well, you'll uncover who wrote this note and why."
    n "Hopefully, you'll also try to locate the bomb and prevent any deaths."
    n "We'll see how you do!"
    
    wait 5

    n "Over the course of the game, feel free to chat to each other. The waiters all have walkie talkies."
    n "The seating arrangement tells you that the group or retirees will sit at three tables."
    n "More guests arrive and get seated. Are you ready to start playing?"    
    jump ask_all_ready

label ask_all_ready(channel="Meta"):
    persistent menu:
        "Start the Game":
            # Update a game variable
            $ ready_count += 1
            if ready_count == num_players:
                n "You all enter the restaurant."
                jump act_1.begin
            jump ask_all_ready
